### ISSUE TITLE
Feature request - change volume id

### ISSUE THREAD

**Issue by hroman73** [bkvarda/xtremlib#2]
Any way to add this?

Thank you

**Comment by bkvarda** [comment]
Can you clarify a bit? I am assuming you have created some volume, and now you would like to change the system-defined ID, and not the name of the volume. If it is the ID, I am not sure that it is possible but will check and see. Is there a specific reason this would be important?

**Comment by hroman73** [comment]
First I'd like to thank you for this...it has made creating snaps and remounting back into vcenter very simple for us with one powershell script that can talk to vcenter, xtremio and our backup service.

We have a set of mission critical servers which we automatically create snaps of, mount the snaps back into vcenter, add the snaps back into vcenter and with a little modification we add the guests in the snaps back into vcenter for backups as well as development teams to test with the code. This script runs every 24 hours. Currently the snaps come into vcenter and vcenter states that the signature must be changed, which we handle from the vcenter side, but I would like to know if it's possible that the vol-id can be changed on the XtremIO side before it's introduced back into vcenter.

Another request is if there is a way to encode the username and password so I don't have to have the current username and password for the XtremIO in the script in plain text.

Regards,
Hector 

On Feb 22, 2015, at 11:51 PM, Brandon Kvarda notifications@github.com wrote:

Can you clarify a bit? I am assuming you have created some volume, and now you would like to change the system-defined ID, and not the name of the volume. If it is the ID, I am not sure that it is possible but will check and see. Is there a specific reason this would be important?

**Comment by bkvarda** [comment]
Hector,

I've made some changes regarding secure credentials...This secures the password only. Pull the new bits and try it out:

```
New-XtremSecureCreds -path C:\temp
```

Now instantiate a new session:

```
New-XtremSession -xioname XIO1 -credlocation C:\temp
```

One thing to note, the key to the password is the Windows account you are setting the secure creds as, and decryption of the password file is only possible on the machine that it was set on (meaning, the user and machine must be the same in order to decrypt). This is using the Windows Data Protection API.

As for changing the volume ID - this is not possible, however I don't believe this would help under you current circumstances. When you take a snap of a volume, the volume ID actually IS already different than the parent volume. The disk signature does not change however, because that was determined by the OS when the parent volume/LUN was initialized and a MBR or GPT was created. When you take a snapshot, the partitions still persist.

**Comment by hroman73** [comment]
This is excellent! Thank you!

As for the vol-id, no worries. It is still possible via resignature via powercli on vsphere but with over 16 datastores that can take quite a while compared to the speed of xtremio.

Thank you again...

Hector

On Mar 01, 2015, at 12:57 PM, Brandon Kvarda notifications@github.com wrote:

Hector,
I've made some changes regarding secure credentials...This secures the password only. Pull the new bits and try it out:
New-XtremSecureCreds -path C:\temp 
Now instantiate a new session:
New-XtremSession -xioname XIO1 -credlocation C:\temp 
One thing to note, the key to the password is the Windows account you are setting the secure creds as, and decryption of the password file is only possible on the machine that it was set on (meaning, the user and machine must be the same in order to decrypt). This is using the Windows Data Protection API.
As for changing the volume ID - this is not possible, however I don't believe this would help under you current circumstances. When you take a snap of a volume, the volume ID actually IS already different than the parent volume. The disk signature does not change however, because that was determined by the OS when the parent volume/LUN was initialized and a MBR or GPT was created. When you take a snapshot, the partitions still persist.
